name: clean_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: 5.0.1
  convex_bottom_bar: 3.0.0
  cupertino_icons: ^1.0.2
  easy_localization: 3.0.1
  fl_chart: 0.40.2
  flutter_bloc: 8.1.1
  flutter_native_splash: 2.2.8
  flutter_screenutil: 5.5.3+2
  fluttertoast: 8.0.9
  get_it: 7.2.0
  hive_flutter: 1.1.0
  http: 0.13.5
  salomon_bottom_bar: 3.3.1
  shimmer: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: 5.0.1
  build_runner: 2.2.0
  flutter_launcher_icons: 0.10.0
  flutter_lints: 2.0.1
  freezed: 2.1.0+1
  hive_generator: 1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
flutter_native_splash:
  color: "#0C0B09"
  image: "assets/images/crypto_splash_screen.png"

flutter_icons:
  image_path: "assets/images/crypto_favicon.png"
  android: true
  ios: true
